#!/bin/sh
# postinst script for tbxsosd-stats
#
# see: dh_installdeb(1)

if [ "$1" = "configure" ]; then
    :
    # Disabled
    #if [ ! -e "/var/cache/tbxsos-stats/rrd/pkg.rrd" -o ! -e "/var/cache/tbxsos-stats/rrd/pkg-delay.rrd" ]; then
	#echo "Init tbxsosd-stats rrd databases."
	#/usr/bin/kstats init
    #fi
fi

